bep/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from privod import views

urlpatterns = [
                  path('', views.Home.as_view(), name='home'),
                  path('category/', views.Categorys.as_view(), name='categorys'),
                  path('category/<str:cat_slug>', views.Products.as_view(), name='products'),
                  path('product/<str:product_slug>', views.SingleProduct.as_view(), name='product'),
                  path('product-tag/<str:tag_slug>', views.ProductTags.as_view(), name='producttag'),
                  path('manufacturer/<str:manufacturer_slug>', views.Manufacturers.as_view(), name='manufacturer'),
                  path('contact/', views.Contacts.as_view(), name='contact'),
                  path('admin/', admin.site.urls),
                  path('editorjs/', include('django_editorjs_fields.urls')),
                  path('search', views.Search.as_view(), name='search'),
                  

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

privod/models.py
import datetime
from django.urls import reverse
from django.db import models
from django_editorjs_fields import EditorJsJSONField

class Category(models.Model):
    cat_name = models.CharField('Название категории продукта', max_length=200)
    cat_title = models.CharField('Заголовок для Open Graph (og:title)', max_length=200, blank=True)
    cat_metadesc = models.CharField('Описание для Open Graph (og:description)', max_length=300, blank=True)
    cat_slug = models.CharField('URL', max_length=200, default='slug' + str(datetime.datetime.now()))
    cat_short_desc = models.TextField('Короткое описание', blank=True)
    pin_main_first = models.BooleanField('Закрепить на главной странице в первом блоке', default=False)
    pin_main_sec = models.BooleanField('Закрепить на главной странице во втором блоке', default=False)
    cat_desccript = EditorJsJSONField(default=dict)
    cat_image = models.ImageField('Изображение категории', default='placeholder.jpg')
    preview_image = models.ImageField('Изображение категории', default='placeholder.jpg')
    pub_date = models.DateTimeField(default=datetime.datetime.now)
    cat_question_1 = models.TextField('Вопрос 1', blank=True, default='')
    cat_question_2 = models.TextField('Вопорос 2', blank=True, default='')
    cat_answer_1 = models.TextField('Ответ 1', blank=True, default='')
    cat_answer_2 = models.TextField('Ответ 2', blank=True, default='')

    def __str__(self):
        return self.cat_name

    def get_absolute_url(self):
        return reverse('products', args=[self.cat_slug])

class Manufacturer(models.Model):
    manufacturer_name = models.CharField('Название производителя', max_length=200)
    manufacturer_title = models.CharField('Заголовок для Open Graph (og:title)', max_length=200)
    manufacturer_metadesc = models.CharField('Описание для Open Graph (og:description)', max_length=300)
    manufacturer_image = models.ImageField('Логотип производителя', default='placeholder.jpg')
    manufacturer_big_image = models.ImageField('Фон производителя', default='placeholder.jpg')
    manufacturer_desc = models.TextField('Описание производителя', blank=True)
    body_editorjs = EditorJsJSONField()
    manufacturer_slug = models.CharField('URL', max_length=200, default='manufacturer' + str(datetime.datetime.now()))

    def __str__(self):
        return self.manufacturer_name

    def get_absolute_url(self):
        return reverse('manufacturer', args=[self.manufacturer_slug])

class Producttag(models.Model):
    tag_name = models.CharField('Название тега', max_length=200)
    tag_title = models.CharField('Заголовок для Open Graph (og:title)', max_length=200)
    tag_metadesc = models.CharField('Описание для Open Graph (og:description)', max_length=300)
    tag_short_desc = models.TextField('Короткое описание', blank=True)
    tag_slug = models.CharField('URL', max_length=200, default='tag' + str(datetime.datetime.now()))

    def __str__(self):
        return self.tag_name

class Product(models.Model):
    product_name = models.CharField('Название продукта', max_length=200)
    product_title = models.CharField('Заголовок для Open Graph (og:title)', max_length=200)
    product_metadesc = models.CharField('Описание для Open Graph (og:description)', max_length=300)
    product_short_desc = models.TextField('Короткое описание', blank=True)
    product_desc = models.TextField('Артикул', blank=True)
    product_image = models.ImageField('Изображение продукта', default='placeholder.jpg')
    pin_main = models.BooleanField('Закрепить на главной странице', default=False)
    category = models.ManyToManyField(Category,blank=True)
    manufacturer = models.ManyToManyField(Manufacturer, blank=True)
    product_tag = models.ManyToManyField(Producttag,blank=True)
    pub_date = models.DateTimeField(default=datetime.datetime.now)
    characteristics = EditorJsJSONField(default=dict)
    longdescription = EditorJsJSONField(default=dict)
    documentationfield = EditorJsJSONField(default=dict)
    product_slug = models.CharField('URL', max_length=200, default='product' + str(datetime.datetime.now()))

    def __str__(self):
        return self.product_name

    def get_absolute_url(self):
        return reverse('product', args=[self.product_slug])

class Article(models.Model):
    article_name = models.CharField('Заголовок H1', max_length=200)
    article_title = models.CharField('Заголовок для Open Graph (og:title)', max_length=200)
    article_metadesc = models.CharField('Описание для Open Graph (og:description)', max_length=300)
    article_slug = models.CharField('URL', max_length=200, default='article' + str(datetime.datetime.now()))
    article_short_desc = models.TextField('Короткое описание для Schema', blank=True)
    article_image = models.ImageField('Изображение статьи')
    isStock = models.BooleanField(default=False)
    body_editorjs = EditorJsJSONField()
    pub_date = models.DateTimeField(default=datetime.datetime.now)

    def __str__(self):
        return self.article_name

    def get_absolute_url(self):
        return reverse('article', args=[self.article_slug])



class Region(models.Model):
    region_name = models.CharField('Название региона', max_length=200)
    region_title = models.CharField('Заголовок для Open Graph (og:title)', max_length=200)
    region_metadesc = models.CharField('Описание для Open Graph (og:description)', max_length=300)
    region_slug = models.CharField('URL', max_length=200, default='region' + str(datetime.datetime.now()))
    region_short_desc = models.TextField('Короткое описание', blank=True)
    body_editorjs = EditorJsJSONField()
    pub_date = models.DateTimeField(default=datetime.datetime.now)

    def __str__(self):
        return self.region_name

    def get_absolute_url(self):
        return reverse('region', args=[self.region_slug])


class Punkt(models.Model):
    punkt_name = models.CharField('Название офиса', max_length=200)
    punkt_title = models.CharField('Заголовок для Open Graph (og:title)', max_length=200)
    punkt_metadesc = models.CharField('Описание для Open Graph (og:description)', max_length=300)
    punkt_short_desc = models.TextField('Короткое описание', blank=True)
    punkt_geo = models.CharField('Описание description', max_length=300, default="55.659173,37.762848")
    punkt_image = models.ImageField('Изображение пункта')
    body_editorjs = EditorJsJSONField()
    punkt_map_key = models.CharField('Ключ карты Яндекс', max_length=200, blank=True)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(default=datetime.datetime.now)
    
    def __str__(self):
        return self.punkt_name

templates/categorys.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="container content-space-t-4 content-space-b-1">
      <div class="w-lg-75">
        <h1 class="display-3 mb-5">
          Категории продуктов,
          <br>
          выберите свою
        </h1>

        <p class="lead"> 5 6 Доставка продукции со склада занимает 1-3 рабочих дней, для выполнения индивидуальных заказов обратитесь к нашим менеджерам</p>
      </div>
    </div>
    <!-- End Hero -->


<div class="container">
      <div class="row mb-2">
          {% for category in categorys %}

        <div class="col-sm-6 col-md-4 mb-4">
          <!-- Card -->
          <div class="card card-bordered shadow-none overflow-hidden">
            <div class="card-body d-flex align-items-center border-bottom p-0">
              <div class="w-65 border-end">
                <img class="img-fluid" src="{{ category.product_set.all.0.product_image.url }}" alt="Image Description">
              </div>
              <div class="w-35">
                <div class="border-bottom">
                  <img class="img-fluid" src="{{ category.product_set.all.1.product_image.url }}" alt="Image Description">
                </div>
                <img class="img-fluid" src="{{ category.product_set.all.2.product_image.url }}" alt="Image Description">
              </div>
            </div>

            <div class="card-footer text-center">
              <h3 class="card-title">{{ category.cat_name }}</h3>
              <p class="card-text text-muted small">{{ category.cat_short_desc }}</p>
              <a class="btn btn-outline-primary btn-sm btn-transition rounded-pill px-6" href="#">Подробнее</a>
            </div>
          </div>
          <!-- End Card -->
        </div>
        <!-- End Col -->
    {% endfor %}

      </div>
      <!-- End Row -->


    </div>


{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load static %} 
{% load editorjs %}
{% block content %}

<div class="container content-space-t-3 content-space-t-lg-5 content-space-b-2">
  <div class="row">
    <div class="col-lg-3 mb-9 mb-lg-0">
      <!-- Heading -->
      <div class="mb-5">
        <h1>Свяжитесь с нами</h1>

      </div>
      <!-- End Heading -->

      <!-- Leaflet -->
      <div class="overflow-hidden">
        <div id="map" class="leaflet mb-5">
          <!-- Form -->

          
            <!-- Form -->
            <div class="mx-auto" style="max-width: 35rem;">
              <!-- Form -->
              <form>

                <!-- Form -->
                <div class="mb-4">

                  <input type="text" class="form-control form-control-lg" name="hireUsFormNameFirstName"
                    id="hireUsFormFirstName" placeholder="Ваше имя" aria-label="Ваше имя">
                </div>
                <!-- End Form -->

                <!-- End Form -->

                <!-- Form -->
                <div class="mb-4">

                  <input type="email" class="form-control form-control-lg" name="hireUsFormNameWorkEmail"
                    id="hireUsFormWorkEmail" placeholder="Ваш телефон или почта" aria-label="Ваш телефон или почта">
                </div>
                <!-- End Form -->

                <!-- Form -->
                <div class="mb-4">
                  <textarea class="form-control form-control-lg" name="hireUsFormNameDetails" id="hireUsFormDetails"
                    placeholder="Пожалуйста напишите Ваш вопрос в этом поле..." aria-label="Пожалуйста напишите Ваш вопрос в этом поле..."
                    rows="4"></textarea>
                </div>
                <!-- End Form -->

                <div class="d-grid mb-2">
                  <button type="submit" class="btn btn-primary btn-lg">Отправить</button>
                </div>

                <div class="text-center">
                  <span class="form-text">Мы ответим вам в ближайшее время</span>
                </div>
              </form>
              <!-- End Form -->
            </div>
            <!-- End Form -->
         
          <!-- End Form -->

          
        </div>
      </div>
      <!-- End Leaflet -->

    </div>
    <!-- End Col -->

    <div class="col-lg-9">
      <div class="ps-lg-5">
        <!-- Card -->

        <div class="text-center">
          <ul class="nav nav-segment nav-pills mb-7" role="tablist">

            {% for region in regions %}
            <li class="nav-item">
              <a class="nav-link navvs" id="{{region.region_slug}}1" href="#{{region.region_slug}}"
                data-bs-toggle="pill" data-bs-target="#{{region.region_slug}}" role="tab" aria-controls="nav-one-eg1"
                aria-selected="false">{{region.region_name}}</a>
            </li>
            {% endfor %}
          </ul>
        </div>
        <!-- End Nav -->

        <!-- Tab Content -->
        <div class="tab-content">
          {% for region in regions %}
          <div class="tab-pane fade" id="{{region.region_slug}}" role="tabpanel">
            <p>
              {% for punkt in region.punkt_set.all %}
              <!-- Card -->
              <div class="container mt-3">
                <div class="w-lg-100 mx-lg-auto">
                  <!-- Card -->
                  <div class="card">
                    <div class="card-body">
                      <div class="row col-md-divider align-items-md-center">
                        <div class="col-md-9">
                          <h3>{{ punkt.punkt_name}}</h3>
                          <p>{{punkt.punkt_short_desc}}</p>

                          <p>{{punkt.body_editorjs | editorjs}}</p>
                          <div>
                            <script type="text/javascript" charset="utf-8" async
                              src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor{{ punkt.punkt_map_key }}&amp;width=100%25&amp;height=300&amp;lang=ru_RU&amp;scroll=true">
                            </script>
                          </div>
                          <div class="row">
                            <div class="col-sm-6 mb-2 mb-sm-0">

                            </div>
                            <!-- End Col -->

                            <div class="col-sm-6">

                            </div>
                            <!-- End Col -->
                          </div>
                          <!-- End Row -->
                        </div>
                        <!-- End Col -->

                        <div class="col-md-3">
                          <div>
                            <h4>Проложить маршрут</h4>
                            <a class="link" href="https://yandex.ru/maps/?rtext=~{{ punkt.punkt_geo }}">Яндекс Карты<i
                                class="bi-chevron-right small ms-1"></i></a>
                          </div>
                        </div>
                        <!-- End Col -->
                      </div>
                      <!-- End Row -->
                    </div>
                  </div>
                  <!-- End Card -->
                </div>
              </div>
              <!-- End Card -->
              {% endfor %}
            </p>
          </div>
          {% endfor %}
          <script>
            document.getElementsByClassName("tab-pane")[0].classList.add('show');
            document.getElementsByClassName("tab-pane")[0].classList.add('active');
            document.getElementsByClassName("navvs")[0].classList.add('active');
          </script>
        </div>
        <!-- End Tab Content -->

      </div>
    </div>
    <!-- End Col -->
  </div>
  <!-- End Row -->

  



  

</div>
<!-- End Contact Form -->


<!-- Info -->
<div class="container mb-5">
  <div class="row justify-content-lg-between">
    <div class="col-lg-2 mb-5 mb-lg-0">
      <h2>Уважаемые коллеги, друзья!</h2>
    </div>
    <!-- End Col -->

    <div class="col-lg-9">
      <p>Мне не хочется начинать это обращение к Вам с фразы: «длительное время» или «динамично развивающаяся» или «вот уже 15 лет» эти штампы не для разговора старых и добрых друзей. Ведь с многими из Вас мы знакомы лично, где помимо строгих и деловых отношений присутствуют и неподдельный интерес о Ваших родных и близких, общих знакомых, желание поздравлять и получать поздравления на праздники. И мы очень ценим эти отношения и это общение. Не буду скрывать, мы всегда рады и новым знакомствам, и новым клиентам.</p>  <p>От команды, зависит все. Один в поле не воин. Идей может быть много, а вот воплотить их в реальность это задача задач, и Вы являетесь частью этого движения.</p>  <p>Мы рады поделиться своим опытом, своими знаниями и умениями. Для себя же главной целью работы ставлю создание команды единомышленников, комфортного делового климата. Треть жизни мы проводим во сне, а треть на работе. Как и в любом живом организме конечно и у нас есть недостатки, мы знаем о них и по силам исправляем. А если подскажете о них будем только рады.</p>  <p>Жизнь- штука непростая. Любит попробовать все на прочность. В терпении возникает надежда, а с надеждой и вера. Вера в то что мы занимаемся нужным и полезным делом, что частичка и нашего труда есть в выращенном зерне, в собранном тракторе, в построенном доме. Отрадно и ответственно! Очень надеемся на Вас дорогие наши коллеги и друзья, на совместный плодотворный труд, на долгосрочные отношения, на взаимопонимание и поддержку.</p>  <p><span style="color: #313131;"><b>Сергей Николаевич</b></span><br> <i>Руководитель компании</i></p>
     </div>
    <!-- End Col -->
  </div>
  <!-- End Row -->






  <div class="row justify-content-lg-between align-items-lg-center">
    <div class="col-lg-6 mb-9 mb-lg-0">
      <!-- Video Block -->
<div id="youTubeVideoPlayer" class="video-player video-player-inline-btn">
  <img class="img-fluid video-player-preview" src="{% static "/video/working-in-office.jpg" %}" alt="Image">

  <!-- Play Button -->
  <a class="js-inline-video-player video-player-btn video-player-centered" href="javascript:;"
     data-hs-video-player-options='{
       "videoId": "jD9j4MxgZgE",
       "parentSelector": "#youTubeVideoPlayer",
       "targetSelector": "#youTubeVideoIframe",
       "isAutoplay": true
     }'>
    <span class="video-player-icon shadow-sm">
      <i class="bi-play-fill"></i>
    </span>
  </a>
  <!-- End Play Button -->

  <!-- Video Iframe -->
  <div class="ratio ratio-16x9">
    <div id="youTubeVideoIframe"></div>
  </div>
  <!-- End Video Iframe -->
</div>
<!-- End Video Block -->
    </div>
    <!-- End Col -->

    <div class="col-lg-5">
      <!-- Heading -->
      <div class="mb-5">
        <h2>Работа нашей команды</h2>
      </div>
      <!-- End Heading -->

      <!-- Step -->
      <ul class="step step-dashed mb-7">
        <li class="step-item">
          <div class="step-content-wrapper">
            <span class="step-icon step-icon-xs step-icon-soft-primary">1</span>
            <div class="step-content">
              <h4 class="step-title">Мы созидательные</h4>
              <p>Мы внимательно относимся к клиенту и осознаем важность нашей деятельности.</p>
            </div>
          </div>
        </li>

        <li class="step-item">
          <div class="step-content-wrapper">
            <span class="step-icon step-icon-xs step-icon-soft-primary">2</span>
            <div class="step-content">
              <h4 class="step-title">Мы ответственные</h4>
              <p>Усердие, увлеченность и ответственность характеризуют нас. Мы ценим каждую деталь наших договоренностей</p>
            </div>
          </div>
        </li>

        <li class="step-item mb-0">
          <div class="step-content-wrapper">
            <span class="step-icon step-icon-xs step-icon-soft-primary">3</span>
            <div class="step-content">
              <h4 class="step-title">Мы любознательные</h4>
              <p class="mb-0">Мы увлеченно работаем и постоянно развиваемся потому что только в постоянном развитии можно добиться прогресса.</p>
            </div>
          </div>
        </li>
      </ul>
      <!-- End Step -->

      <a class="btn btn-primary btn-transition" href="#">Заказать звонок</a>
    </div>
    <!-- End Col -->
  </div>
  <!-- End Row -->

</div>
<!-- End Info -->




{% endblock %}

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% load editorjs %}
{% block content %}
<main id="content" role="main" class="content-space-t-4">
    <!-- Breadcrumb -->
    <div class="border-top border-bottom">
      <div class="container py-3">
        <!-- Breadcrumb -->
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item">
              <a href="{% url 'products' product.category.first.cat_slug %}">{{product.category.first}}</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">{{product.product_name}}</li>
          </ol>
        </nav>
        <!-- End Breadcrumb -->
      </div>
    </div>
    <!-- End Breadcrumb -->

    <!-- Content -->
    <div class="container content-space-t-2 content-space-b-lg-2">
      <div class="row">
        <div class="col-md-4 col-lg-4 mb-9 mb-md-0">
          <div class="pe-lg-2">
            <div class="text-center mb-4">
              <img class="product-image " src="{{ product.product_image.url }}" alt="Logo">
            </div>

            <div class="d-grid mb-5">
              <a class="btn btn-sm-p1  btn-block btn-primary transition-3d-hover" href="#">Заказать звонок</a>
              
            </div>
            <div class="mb-5 d-flex justify-content-between">
              <div>
                <img class="h-30" src="{% static '/vendor/duotone-icons/com/com014.svg' %}" /><span class="text-dark h5">1 год гарантии</span>
              </div>
              <div>
              <img class="h-30" src="{% static '/vendor/duotone-icons/com/com007.svg' %}" /><span class="text-dark h5">Проведем рассчеты</span>
            </div>
            </div>

<!-- Banner -->
<div class="pb-5">
  <div class="bg-light rounded-2" style="background: url({% static '/svg/components/shape-6.svg' %}) right bottom no-repeat;">
    <div class="py-8 px-6">
      <h5 class="">Сломался редуктор?</h5>
      <p class="mb-0">Купите новый или <a class="link link-primary" href="#">закажите ремонт</a></p>
    </div>
  </div>
</div>
<!-- End Banner -->



            <div class="mb-7">
              {% if product.product_tag.first %}
              <h1 class="h4">Назначение</h1>
              {% endif %}
{% for cat in product.product_tag.all%}
              <a class="btn btn-soft-secondary btn-xs me-1 mb-2" href="{% url 'producttag' cat.tag_slug%}">{{ cat }}</a>
{% endfor %}
            </div>

            <div class="d-none d-md-block mb-7">
              {% if product.manufacturer.first %}
              <h4>Производитель</h4>
              {% endif %}
              {% for manufact in product.manufacturer.all %}

              <a class="d-flex align-items-center" href="{% url 'manufacturer' manufact.manufacturer_slug%}">
                <div class="flex-shrink-0">
                  <img class="avatar avatar-xs" src="{{ manufact.manufacturer_image.url}}" alt="Logo">
                </div>
                <div class="flex-grow-1 ms-2">
                  <span class="link link-secondary">{{manufact}}</span>
                </div>
              </a>
              {% endfor %}
            </div>

        

            
          </div>
        </div>
        <!-- End Col -->

        <div class="col-md-8 col-lg-8 column-divider-md">
          <div class="ps-lg-2">
            <div class="mb-5">
              <h2>{{ product.product_name }}</h2>
              <div>{{ product.product_short_desc }}</div>
            </div>

            <!-- Nav Scroller -->
            <div class="js-nav-scroller hs-nav-scroller-horizontal">
              <span class="hs-nav-scroller-arrow-prev" style="display: none;">
                <a class="hs-nav-scroller-arrow-link" href="javascript:;">
                  <i class="bi-chevron-left"></i>
                </a>
              </span>

              <span class="hs-nav-scroller-arrow-next" style="display: none;">
                <a class="hs-nav-scroller-arrow-link" href="javascript:;">
                  <i class="bi-chevron-right"></i>
                </a>
              </span>

              <!-- Nav -->
              <ul class="nav nav-segment nav-fill mb-7" id="featuresTab" role="tablist">
                <li class="nav-item" role="presentation">
                  <a class="nav-link active" href="#featuresOne" id="featuresOne-tab" data-bs-toggle="tab" data-bs-target="#featuresOne" role="tab" aria-controls="featuresOne" aria-selected="true" style="min-width: 7rem;">Описание</a>
                </li>

                <li class="nav-item" role="presentation">
                  <a class="nav-link" href="#featuresTwo" id="featuresTwo-tab" data-bs-toggle="tab" data-bs-target="#featuresTwo" role="tab" aria-controls="featuresTwo" aria-selected="false" style="min-width: 7rem;">Характеристики</a>
                </li>

                <li class="nav-item" role="presentation">
                  <a class="nav-link" href="#featuresThree" id="featuresThree-tab" data-bs-toggle="tab" data-bs-target="#featuresThree" role="tab" aria-controls="featuresThree" aria-selected="false" style="min-width: 7rem;">Документация</a>
                </li>
              </ul>
              <!-- End Nav -->
            </div>
            <!-- End Nav Scroller -->

            <!-- Tab Content -->
            <div class="tab-content" id="pills-tabContent">
              <div class="tab-pane fade show active" id="featuresOne" role="tabpanel" aria-labelledby="featuresOne-tab">
               {{ product.longdescription | editorjs }}
              </div>

              <div class="tab-pane fade" id="featuresTwo" role="tabpanel" aria-labelledby="featuresTwo-tab">
                {{ product.characteristics | editorjs }}
              </div>

              <div class="tab-pane fade" id="featuresThree" role="tabpanel" aria-labelledby="featuresThree-tab">
                {{ product.documentationfield | editorjs }}
            </div>
            <!-- End Tab Content -->
          </div>
        </div>
        <!-- End Col -->
      </div>
      <!-- End Row -->
    </div>
    <!-- End Content -->

    <!-- Card Grid -->
    <div class="container content-space-2">
      <!-- Heading -->
      <div class="d-flex justify-content-between align-items-center mb-3">
        <h3 class="mb-0">Смотрите также</h3>
        <a class="link" href="{% url 'products' product.category.first.cat_slug %}">{{product.category.first}}<i class="bi-chevron-right small ms-1"></i></a>
      </div>
      <!-- End Heading -->

  
     


      <div class="row gx-3 mx-n2">

        {% for reccomend in product.category.first.product_set.all %}
        {% if forloop.counter < 7 %}
        <div class="col-sm-6 col-md-4 mb-3">
          <!-- Card -->
          <div class="card card-bordered card-transition shadow-none h-100">
            <a class="card-body" href="{% url 'product' reccomend.product_slug %}">
              <div class="d-flex">
                <div class="flex-shrink-0">
                  <img class="avatar" style="height:auto;" src="{{ reccomend.product_image.url }}" alt="Logo">
                </div>

                <div class="flex-grow-1 ms-3">
                  <div class="d-flex align-items-center">
                    <h5 class="card-title mb-0">{{ reccomend.product_name}}</h5>

                  </div>
                  <p class="card-text text-body small">{{ reccomend.manufacturer.first.manufacturer_name }}</p>
                </div>
              </div>
            </a>
          </div>
          <!-- End Card -->
        </div>
        <!-- End Col -->
        {% endif %}
        {% endfor %}
        
      </div>
      <!-- End Row -->
    </div>
    <!-- End Card Grid -->
  </main>
{% endblock %}

templates/products.html
{% extends 'base.html' %}
{% load static %}
{% load editorjs %}
{% block content %}
<div style="background-image: url({% static '/svg/components/card-11.svg' %});">
<div class="container content-space-t-4">
  <div class="w-lg-75">
    <h1 class="mb-5">
      {{ category.cat_name }}
    </h1>

    <p class="lead">{{ category.cat_short_desc }}</p>
  </div>
</div>
<!-- End Hero -->

<!-- Card Grid -->
<div class="container content-space-t-1">
  <div class="row">
    <div class="col-lg-12">
      <div class="row row-cols-sm-2 row-cols-md-4 mb-10">
        {% for product in category.product_set.all %}
        <div class="col-sm-6 col-lg-3 my-5 mb-lg-0">
          <!-- Card -->
          <div class="card card-sm shadow-sm mb-4" style="height: 100%">
            <div class="card-body">
              <div style="
                        display: flex;
                        flex-wrap: wrap;
                        flex-direction: column;
                        height: 100%;
                        justify-content: space-between;
                      ">
                <div>
                  <div style="width: auto; height: 200px;overflow:hidden;">
                    <img style="
                          width: 100%;
                          " src="{{ product.product_image.url }}" alt="Image Description" />
                  </div>
                  <h3 class="card-title">{{ product.product_name }}</h3>
                  <p class="card-text">{{product.category.all.0}}</p>
                  {% if product.manufacturer.all.0.manufacturer_image.url %}
                  <div class="mb-4">
                    <img class="avatar avatar-4x3 me-2" src="{{product.manufacturer.all.0.manufacturer_image.url}}"
                      alt="Figma" />
                  </div>
                  {% endif %}
                </div>
                <div>
                  <a href="{% url 'product' product.product_slug %}">
                    <button type="button" class="btn btn-outline-secondary">
                      Подробнее
                    </button></a>
                </div>
              </div>
            </div>
          </div>
          <!-- End Card -->
        </div>
        <!-- End Col -->
        {% endfor %}
      </div>
      <!-- End Row -->
      {{category.cat_desccript | editorjs }}

    </div>
    <!-- End Col -->
  </div>
  <!-- End Row -->
</div>
<!-- End Card Grid -->

<!-- Clients -->
<div class="container content-space-2">
  <div class="row">
    {% for manufacturer in manufacturers %}
    <div class="col text-center py-3">
      <img class='ah-50' src="{{ manufacturer.manufacturer_image.url }}" alt="Logo">
    </div>
    <!-- End Col -->
    {% endfor %}
  </div>
  <!-- End Row -->
</div>
<!-- End Clients -->
</div>
{% endblock %}